codecov:
  require_ci_to_pass: true

comment:
   behavior: default
   branches:
      - 'main'

coverage:
   round: 'down'
   range: 90..100
   status:
      project:
         default:
            target: auto
            threshold: 0.5%
