name: build

on: [push, pull_request]

jobs:
  # Unittests
  unittests:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        python-version: [3.8, 3.11]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        shell: bash
        run: |
          pip install numpy
          pip install -i https://test.pypi.org/simple/ "scikit-misc==0.2.0rc3"
          pip install ".[extra,testing]"

      - name: Environment Information
        shell: bash
        run: |
          pip list

      - name: Run Tests
        shell: bash
        run: |
          coverage erase
          make test

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: result-images
          path: tests/result_images/
          if-no-files-found: ignore

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          name: "py${{ matrix.python-version }}"

  # Linting
  lint:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        shell: bash
        run: |
          pip install ruff
          pip install black

      - name: Environment Information
        shell: bash
        run: pip list

      - name: Lint with Ruff
        shell: bash
        run: |
          make lint

      - name: Lint with Black
        shell: bash
        run: |
          make black


  # Typecheck
  typecheck:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        shell: bash
        run: |
          pip install numpy
          pip install -i https://test.pypi.org/simple/ "scikit-misc==0.2.0rc3"
          pip install ".[extra]"
          pip install -r requirements/typing.txt

      - name: Environment Information
        shell: bash
        run: pip list

      - name: Run Tests
        shell: bash
        run: make typecheck


  # Documentation
  documentation:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        shell: bash
        run: |
          sudo apt-get install pandoc
          pip install ".[testing,doc]"
          pip install -r requirements/doc.txt

      - name: Environment Information
        shell: bash
        run: pip list

      - name: Build Documentation
        shell: bash
        run: |
          pushd doc
          SPHINXOPTS=-W
          make html && popd
