name: build

on: [push, pull_request]

jobs:
  unittests:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        python-version: [3.9, 3.12]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        shell: bash
        run: |
          pip install ".[extra,test]"

      - name: Environment Information
        shell: bash
        run: |
          pip list

      - name: Run Tests
        shell: bash
        run: |
          coverage erase
          make test

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: result-images
          path: tests/result_images/
          if-no-files-found: ignore

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          name: "py${{ matrix.python-version }}"

  lint-and-format:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        shell: bash
        run: |
          pip install ruff

      - name: Environment Information
        shell: bash
        run: pip list

      - name: Check lint with Ruff
        shell: bash
        run: |
          make lint

      - name: Check format with Ruff
        shell: bash
        run: |
          make format

  typecheck:
    runs-on: ubuntu-latest

    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Packages
        shell: bash
        run: |
          pip install ".[extra, typing]"

      - name: Environment Information
        shell: bash
        run: pip list

      - name: Run Tests
        shell: bash
        run: make typecheck

  call-build-documentation:
    if: |
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/documentation.yml
